[package]
name = "neverest"
description = "CLI to synchronize and backup emails"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities", "email"]
keywords = ["cli", "email", "imap", "backup", "sync"]
homepage = "https://pimalaya.org/"
documentation = "https://pimalaya.org/neverest/cli/latest/"
repository = "https://github.com/soywod/neverest/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--document-private-items"]

[features]
default = [
  # Enables the IMAP backend, which allows the synchronizer to connect
  # to remote IMAP servers.
  #
  # doc: <https://pimalaya.org/neverest/cli/latest/configuration/imap.html>
  "imap",

  # Enables the Maildir backend, which allows the synchronizer to
  # access your emails locally, using the file system.
  #
  # spec: <https://cr.yp.to/proto/maildir.html>
  # doc: <https://pimalaya.org/neverest/cli/latest/configuration/maildir.html>
  "maildir",

  # Enables the Notmuch backend, which allows the synchronizer to
  # access your emails locally, using the Notmuch email system. This
  # feature turns on the maildir feature, since Notmuch requires a
  # Maildir folder to operate. This feature also requires the
  # libnotmuch to be installed and available on your system.
  #
  # site: <https://notmuchmail.org/>
  # doc: <https://pimalaya.org/neverest/cli/latest/configuration/notmuch.html>
  # "notmuch",

  # Enables the wizard configurator, which interactively helps you to
  # configure your default account. It also automatically discovers
  # remote IMAP settings from your email address.
  #
  # doc: <https://pimalaya.org/neverest/cli/latest/configuration/index.html#automatically-using-the-wizard>
  "wizard",
]

imap = ["email-lib/imap"]
maildir = ["email-lib/maildir"]
notmuch = ["email-lib/notmuch"]
wizard = [
  "dep:console",
  "dep:email_address",
  "dep:oauth-lib",
  "dep:secret-lib",
  "dep:toml_edit",
  "email-lib/account-discovery",
]

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.2"
console = { version = "0.15.2", optional = true }
dialoguer = "0.10.2"
dirs = "4"
email-lib = { version = "=0.23.1", default-features = false, features = ["account-sync", "derive"] }
email_address = { version = "0.2.4", optional = true }
env_logger = "0.8"
erased-serde = "0.3"
indicatif = "0.17"
log = "0.4"
mml-lib = { version = "=1.0.11", default-features = false }
oauth-lib = { version = "=0.1.1", optional = true }
once_cell = "1.16"
secret-lib = { version = "=0.4.4", optional = true, features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde-toml-merge = "0.3"
serde_json = "1"
shellexpand-utils = "=0.2.1"
termcolor = "1"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt-multi-thread"] }
toml = "0.8"
toml_edit = { version = "0.22", optional = true }

[target.'cfg(not(windows))'.dependencies]
coredump = "0.1"
