name: release

on:
  push:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'version-${{ github.sha }}'
          release_name: 'version-${{ github.sha }}'
          draft: false
          prerelease: false

  deploy-unix-releases:
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux
            os: ubuntu-latest
          - target: linux-musl
            os: ubuntu-latest
          - target: macos
            os: macos-latest
          # TODO: uncomment once nix build .#windows works
          - target: windows
            os: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: soywod
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build release
        run: nix build -L .#${{ matrix.target }}
      - name: Copy binary
        run: |
          cp result/bin/neverest* .
      - name: Patch binary interpreter
        if: ${{ matrix.target == 'linux' }}
        run: |
          nix-shell -p patchelf --command "sudo patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 neverest"
      - name: Prepare release archives
        run: |
          mkdir -p {man,completions}
          nix run .#${{ matrix.target }} man ./man
          nix run .#${{ matrix.target }} completion bash > ./completions/neverest.bash
          nix run .#${{ matrix.target }} completion elvish > ./completions/neverest.elvish
          nix run .#${{ matrix.target }} completion fish > ./completions/neverest.fish
          nix run .#${{ matrix.target }} completion powershell > ./completions/neverest.powershell
          nix run .#${{ matrix.target }} completion zsh > ./completions/neverest.zsh
          tar -czf neverest.tgz neverest* man completions
          zip -r neverest.zip neverest* man completions
      - name: Upload tarball release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: neverest.tgz
          asset_name: neverest-${{ matrix.target }}.tgz
          asset_content_type: application/gzip
      - name: Upload zip release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: neverest.zip
          asset_name: neverest-${{ matrix.target }}.zip
          asset_content_type: application/zip

  # TODO: remove me once nix build .#windows works
  # deploy-windows-release:
  #   runs-on: windows-latest
  #   needs: create-release
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         profile: minimal
  #     - name: Build release
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --release
  #     - name: Copy binary
  #       run: |
  #         copy target/release/neverest.exe .
  #     - name: Prepare release archives
  #       run: |
  #         mkdir man
  #         mkdir completions
  #         ./neverest.exe man ./man
  #         ./neverest.exe completion bash > ./completions/neverest.bash
  #         ./neverest.exe completion elvish > ./completions/neverest.elvish
  #         ./neverest.exe completion fish > ./completions/neverest.fish
  #         ./neverest.exe completion powershell > ./completions/neverest.powershell
  #         ./neverest.exe completion zsh > ./completions/neverest.zsh
  #         tar -czf neverest.tgz neverest.exe man completions
  #         Compress-Archive -Path neverest.exe,man,completions -DestinationPath neverest.zip
  #     - name: Upload tarball release archive
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ needs.create-release.outputs.upload_url }}
  #         asset_path: neverest.tgz
  #         asset_name: neverest-windows.tgz
  #         asset_content_type: application/gzip
  #     - name: Upload zip release archive
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ needs.create-release.outputs.upload_url }}
  #         asset_path: neverest.zip
  #         asset_name: neverest-windows.zip
  #         asset_content_type: application/zip
